final List<Map<String, dynamic>> allPets = [
  {
    'name': 'Andre',
    'location': 'Panabo City',
    'age': '1 yrs',
    'image': 'assets/dog1.jpg',
    'gender': 'male',
    'type': 'dog',
  },
  {
    'name': 'Cases',
    'location': 'Panabo City',
    'age': '2 yrs',
    'image': 'assets/dog2.jpg',
    'gender': 'male',
    'type': 'dog',
  },
  {
    'name': 'Cassie',
    'location': 'Panabo City',
    'age': '3 yrs',
    'image': 'assets/cat2.jpg',
    'gender': 'female',
    'type': 'cat',
  },
  {
    'name': 'Luna',
    'location': 'Davao City',
    'age': '1.5 yrs',
    'image': 'assets/cat1.jpg',
    'gender': 'female',
    'type': 'cat',
  },
  {
    'name': 'Max',
    'location': 'Tagum City',
    'age': '4 yrs',
    'image': 'assets/dog3.jpg',
    'gender': 'male',
    'type': 'dog',
  },
  {
    'name': 'Oreo',
    'location': 'Panabo City',
    'age': '2 yrs',
    'image': 'assets/rabbit1.jpg',
    'gender': 'male',
    'type': 'rabbit',
  },
];
